In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [3]:
type(my_list)

list

## Creating NumPy Arrays from Objects

### From a Python List

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods to create arrays

### arange

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [16]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``.

In [18]:
np.random.rand(2)

array([0.14007794, 0.80383   ])

In [19]:
np.random.rand(5,5)

array([[0.72436338, 0.51686567, 0.44317409, 0.0748358 , 0.8673325 ],
       [0.15881894, 0.01358168, 0.65849979, 0.69715063, 0.47728184],
       [0.45482336, 0.62000967, 0.12087288, 0.5286604 , 0.00257297],
       [0.68099253, 0.08927805, 0.87175977, 0.99344868, 0.13927708],
       [0.54392398, 0.4939343 , 0.3509071 , 0.88916408, 0.13085935]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear.

In [20]:
np.random.randn(2)

array([-0.8954136 ,  0.12577637])

In [21]:
np.random.randn(5,5)

array([[ 0.09420119,  0.60235521, -2.06216986,  0.14364123,  2.12413623],
       [ 0.75805619,  0.6060581 ,  1.10157673, -0.78876961, -0.31044582],
       [ 1.56286219,  0.37248205, -0.74461715,  0.20642655,  0.80273155],
       [ 0.35817517, -1.31164362,  0.13022779, -0.24201713,  2.01498609],
       [ 0.36768946,  0.38036576,  0.61828225, -0.46349144, -0.42557544]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

91

In [23]:
np.random.randint(1,100,10)

array([67, 24, 42, 27, 52, 28,  9, 24, 73,  2])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced.

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [31]:
ranarr.max()

39

In [32]:
ranarr.argmax()

7

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int64')

In [41]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')